name: pr
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.13
  - pip
  - ipykernel
  - ipython
  - jupyter_client
  - jupyter_core
  - matplotlib-inline
  - numpy
  - pandas
  - scipy
  - matplotlib
  - psutil
  - pyzmq
  - setuptools
  - wheel
  - pip:
      - cfgv==3.4.0
      - contourpy==1.3.3
      - cycler==0.12.1
      - distlib==0.4.0
      - filelock==3.19.1
      - fonttools==4.59.1
      - graphviz==0.21
      - identify==2.6.13
      - iniconfig==2.1.0
      - kiwisolver==1.4.9
      - nodeenv==1.9.1
      - pillow==11.3.0
      - pluggy==1.6.0
      - pre-commit==4.3.0
      - pyparsing==3.2.3
      - pytest==8.4.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - ruff==0.12.10
      - seaborn==0.13.2
      - tzdata==2025.2
      - virtualenv==20.34.0